#include "include.h"
#include "defs.h"
#include "data_structure_types.h"
#include "chapter_3.h"

#include "chapter_3_1.c"
#include "chapter_3_2.c"
#include "chapter_3_6.c"
#include "chapter_3_9.c"
#include "chapter_3_10.c"
#include "chapter_3_16.c"
